### ISSUE TITLE
Matplotlib Support 

### ISSUE THREAD

**Issue by abelREK** [cachix/devenv#1222]
Trying to get matplotlib to show a graph but get the follow error. 
UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
Any pointers on how to resolve this issue? 

I have tried installing PYQT6.

**Comment by sandydoo** [comment]
We can't really help without a working example. Maybe someone in [our discord](https://discord.com/channels/1036369714731036712/1036369758024650792) can help you out.

This doesn't seem like a devenv issue, so I'm going to close this. Feel free to reopen if that changes.

**Comment by jolars** [comment]
I'm also running into this. I don't think it's a devenv issue either, but perhaps it is something that devenv could help mitigate? 

Did you ever find a solution, @abelREK ?

**Comment by sandydoo** [comment]
If you're on Linux and are set on using QT, read on.

#### The easy approach

1. Add `pkgs.python3Packages.pyqt6` to `packages` in `devenv.nix`. This will bring in all of the dependencies you need.
2. Configure matplotlib to use QT with `matplotlib.use('QtAgg')`

#### The manual approach

Installing PyQt6 with pip or poetry is not enough because QT has a gigantic list of dependencies on Linux.

1. Add the following packages:
```nix
  packages = [
    pkgs.zlib
    pkgs.glib
    pkgs.zstd
    pkgs.libGL
    pkgs.libdrm
    pkgs.dbus
    pkgs.udev
    pkgs.fontconfig
    pkgs.freetype
    pkgs.xorg.libX11
    pkgs.xorg.libXcomposite
    pkgs.xorg.libXext
    pkgs.xorg.libXi
    pkgs.xorg.libXrender
    pkgs.xorg.libxcb
    pkgs.libxkbcommon
    pkgs.xorg.xcbutil
    pkgs.xorg.xcbutilimage
    pkgs.xorg.xcbutilkeysyms
    pkgs.xorg.xcbutilrenderutil
    pkgs.xorg.xcbutilwm
  ];
```
2. Configure matplotlib to use QT with `matplotlib.use('QtAgg')`

matplotlib tries to be smart by trying to import every possible compositor until one works, but at the same time it hides the actual import error. This is what it tries to import:
```
python3 -c 'from PyQt6 import QtCore, QtGui, QtWidgets, sip'
```

If you run it yourself, you'll notice that it throws a much more helpful error, like `ImportError: libglib-2.0.so.0: cannot open shared object file: No such file or directory`. Now you can start figuring out which dependencies you're missing.

**Comment by sandydoo** [comment]
Another option is to use tkinter. It's normally shipped with python, but it's a separate package on nixpkgs.

devenv.nix
```nix
{ pkgs, ... }: {
  languages.python = {
    enable = true;
    venv.enable = true;
    # Set up your venv with pip or poetry or uv here
    # uv.enable = true;
    # uv.sync.enable = true;
    package = pkgs.python3.withPackages (p: [
      p.tkinter
    ]);
  };
}
```

```python
import matplotlib
import matplotlib.pyplot as plt
matplotlib.use('TkAgg')

# ...
```

**Comment by abelREK** [comment]
@jolars https://github.com/abelREK/devenv_python_data_science_example

Just learned that as a rule of thumb to use the nix packages version of libraries as much as possible.
