### ISSUE TITLE
A mode that takes the inputs from a flake instead of yaml

### ISSUE THREAD

**Issue by roberth** [cachix/devenv#233]
**Describe the ~bug~ improvement**

When trying this out with a flake, I was surprised to find that devenv still writes its own lock file. I think it should be possible to read the inputs from a `flake.nix` + `flake.lock` instead of `devenv.lock`.
If the yaml doesn't specify `inputs`, it could scan the flake inputs for a devenv-related attribute.

**To Reproduce**

Follow the flake instructions and add the `devenv` command to the shell. Run `devenv search hello`

**Version**

 devenv: 0.5
88afd0d

**Comment by domenkozar** [comment]
That's probably too much magic, ideally there would be a flag in `flake.nix` that would turns this behavior on.

I'd really like to see this done, but it's not on my priority list, if someone wants to take a try I'm happy to help!

**Comment by domenkozar** [comment]
flake integration could set something like DEVENV_USING_FLAKES=1 and then devenv command can respect that and use `flake.*` files

**Comment by thenonameguy** [comment]
> flake integration could set something like DEVENV_USING_FLAKES=1 and then devenv command can respect that and use `flake.*` files

I brainstormed around this problem quite a bit in the past 2 weeks. 

Instead of introducing conditional logic everywhere in devenv CLI/modules IMO the cleaner and more standards compliant way would be to eschew the "hidden" flake altogether and migrate the existing CLI code to use https://github.com/hercules-ci/flake-parts as an internal implementation detail + an actual `flake.nix`/`flake.lock`
This way `devenv init` would create an initial `flake.nix` if it not exists (similar to the current Flake template).

New users can be told to ignore this file for the most part, while implementing the devenv CLI experience as a flake-part module.
Advanced Nix users can still package their applications via Flakes, by having complete control over the flake.nix.

I'll try to create a POC soon.

**Comment by roberth** [comment]
@thenonameguy I made a bit of progress on such a module [here](https://github.com/cachix/devenv/compare/main...hercules-ci:devenv:flake-module?expand=1), but stopped because of this issue. The documentation file is basically just a copy of the flakes one; you can ignore that.

**Comment by domenkozar** [comment]
https://github.com/cachix/devenv/pull/284 changed flakes integration to ship a small `devenv` shim that works with flakes

**Comment by domenkozar** [comment]
I'm going to close this as I think it's fixed, let me know if that's not the case.

**Comment by roberth** [comment]
Awesome. I've opened #360 for the flake module. It uses pretty much the same wiring as the bare flakes template, so the CLI thing is orthogonal anyway.
