### ISSUE TITLE
Generate ``devcontainer.json``

### ISSUE THREAD

**Issue by domenkozar** [cachix/devenv#26]
https://containers.dev/implementors/json_reference/#general-properties

**Comment by domenkozar** [comment]
https://twitter.com/domenkozar/status/1594282602059661313

**Comment by hugosenari** [comment]
yo dawg i heard you like _config_,
so write a module to write [files from _config_](https://cruel-intentions.github.io/devshell-files/modules/files.html),
then write a module to convert structured nix to these _configs_ as [json, yaml, toml, txt](https://github.com/cruel-intentions/devshell-files/blob/master/modules/file-format.nix),
then add module that use previous _config_ to write your devcontainer.json 
Or [whatever](https://cruel-intentions.github.io/gh-actions/options.html#gh-actions) your user want on top of that.

Personal note:
I prefer single binary commands like yj or even a nushell [helper](https://github.com/cruel-intentions/devshell-files/blob/master/examples/nushell/nuon.nix) 
than python like in pkgs lib [formater](https://github.com/NixOS/nixpkgs/blob/master/pkgs/pkgs-lib/formats.nix#L63), 
because the final closure size.


Random [note](https://knowyourmeme.com/memes/xzibit-yo-dawg):
> This multi-layered structure in the Yo Dawg formula makes it reminiscent of the"strange loops" described in Douglas Hofstadter's Gödel, Escher, Bach.

**Comment by domenkozar** [comment]
https://github.com/cachix/devenv/pull/142
