### ISSUE TITLE
venv becomes stale after some time (nix store gc?)

### ISSUE THREAD

**Issue by farcaller** [cachix/devenv#336]
**Describe the bug**
venv breaks down after not touching it for a couple days. I have `nix.gc.automatic = true` enabled.

```
$ pip install polars
exec: Failed to execute process '/Users/farcaller/src/example/.devenv/state/venv/bin/pip': The file specified the interpreter '/Users/farcaller/src/example/.devenv/state/venv/bin/python', which is not an executable command.

$ ls -l /Users/farcaller/src/example/.devenv/state/venv/bin/pip
.rwxr-xr-x@ 267 farcaller 25 Jan 13:22 /Users/farcaller/src/example/.devenv/state/venv/bin/pip

$ ls -l /Users/farcaller/src/example/.devenv/state/venv/bin/python
lrwxr-xr-x@ 69 farcaller 25 Jan 13:22 /Users/farcaller/src/example/.devenv/state/venv/bin/python -> /nix/store/dchvlb6c2qn78b4623xsfrm7kqa2487g-devenv-profile/bin/python

$ stat /nix/store/dchvlb6c2qn78b4623xsfrm7kqa2487g-devenv-profile/bin/python
stat: /nix/store/dchvlb6c2qn78b4623xsfrm7kqa2487g-devenv-profile/bin/python: stat: No such file or directory
```

**To Reproduce**
https://gist.github.com/farcaller/57670b22ecb6e91f82a41a95a0637f1d

**Version**
 
devenv: 0.5

**Comment by domenkozar** [comment]
We should scan DEVENV_STATE and put all store paths in there as a GC root.

**Comment by domenkozar** [comment]
What happens here is that the python that devenv provisioned that created the virtualenv is gc-ed because it's no longer part of the latest environment (for example in case it gets updated in nixpkgs).

Once the users runs the garbage collection, python interpreter hardcoded in bin/python is gone.

@bobvanderlinden any ideas how to fix this beyond scanning `DEVENV_STATE` for nix store paths?

**Comment by bobvanderlinden** [comment]
This is a problem that I assume also happens with native packages in node_modules and ruby gems. Whenever the state links to something in /nix/store.

I have thought about including the store path of python/nodejs/ruby to the state dir, but thought it might be changing too often. Maybe it is better to do this anyway.

So, instead of using `.devenv/state/venv`, it would by `.devenv/state/XXX-python-3.10-venv`. It does need rebuilding each time nixpkgs is updated, but it does stay stable. More stability, less convenient?

**Comment by bobvanderlinden** [comment]
I have been thinking about this some more. There are a few options. The blunt ones first :sweat_smile::

* Rebuild venv every time the devenv profile changes.
  * Reliable, because it will always work correctly
  * Slow and annoying when you change devenv.nix often
* Scan `DEVENV_STATE` for `/nix/store` references.
  * Hard to get right and know for sure it is working reliably
  * Not sure how to go about implementing this
* Only rebuild when python binary needs to change.
  * Make sure venv uses the symlink-resolved paths (like `/nix/store/XXX-python/bin/python` instead of `/nix/store/XXX-devenv-profile/bin/python`, so that it doesn't rely on devenv profiles.
  * Always check the `$DEVENV_STATE/venv/bin/python` symlink against `${languages.python.package}/bin/python`. Rebuild venv when changed.
  * Not _really_ reliable, as there might be other dependencies that were changed and are still being incorrectly referred to in the venv.
* Let Nix build the python environment from project.toml and poetry.lock.
  * Use something like dream2nix to do this.
  * The poetry cli will have trouble with handling its packages
  * Not ergonomic for existing python developers
  * Unclear how to do updates of poetry.lock

I think rebuilding currently sounds like the only viable option.
Any alternatives that I've missed? Otherwise I'll look into implementing this.
