### ISSUE TITLE
direnv: faster loading

### ISSUE THREAD

**Issue by kubukoz** [cachix/devenv#35]
Currently, if you use direnv you'll get a note saying it takes too long to export:

<img width="2395" alt="image" src="https://user-images.githubusercontent.com/894884/201531257-4b9c98d5-b9fa-49c9-a2b8-ebcb6a2ae1d5.png">

Is it possible to devenv to perform an export of everything it needs, like the normal `nix develop` does when used with direnv?

**Comment by domenkozar** [comment]
That's what it does, but it will always reevaluate shell to make sure it's up to date.

To properly fix this, we need to get Nix to be fast.

**Comment by kubukoz** [comment]
Are you sure? I think it's showing that because the `direnv export zsh` command here just lasts as long as I'm in the shell.

**Comment by hugosenari** [comment]
I did this for a [similar problem](https://github.com/cruel-intentions/devshell-files/blob/master/modules/direnv.nix#L11):
- create a directory for direnv, `direnv_layout_dir` gives us the dir path
- compare watched files `$(cmp --silent -- <(echo "$DIRENV_WATCHES") "${direnv_layout_dir}/session")`
  - if its different write a cache file into direnv_layout_dir with result of  `$(./result/bin/devenv print-dev-env)`
  - and write session file tested before
- eval from cache


Not solve the problem, but make it noticeable only when environment changes.

Possible issues: I'm not sure what happens when we use different [direnv layouts](https://direnv.net/man/direnv-stdlib.1.html#codelayout-lttypegtcode)

**Comment by domenkozar** [comment]
Could you give this one a try: https://github.com/cachix/devenv/commit/4717da802b1868318ab60758c244c4b37774f426

**Comment by kubukoz** [comment]
Sorry, I keep marking this as unread to finally check it when I have some time. I'll check it out this weekend.

**Comment by terlar** [comment]
I am just testing this out and use 0.5 which should include this I presume, but the `.envrc` that gets generated looks like this:
```
$ cat .envrc
watch_file devenv.nix 
watch_file devenv.yaml 
watch_file devenv.lock
eval "$(devenv print-dev-env)"
```

and the `devenv print-dev-env` command takes 4-5 seconds. Also miss the speed of my previous setup using the `use flake` together with `nix-direnv` support which has sub-second performance.

**Comment by thenonameguy** [comment]
Yes, nix-direnv only works with 0.5 if you still take the Flake route of the devenv integration. See the default template's .envrc/flake.nix how that looks.

**Comment by domenkozar** [comment]
@shyim reports success using https://github.com/indigoviolet/direnv-cache

**Comment by thenonameguy** [comment]
I made some progress trying to get the same evaluation path as `devenv print-dev-env` does in the current `.envrc` template, while reusing the great effort put into caching and avoiding unnecessary evaluations:
https://github.com/cachix/devenv/pull/237

The problem is the `devenv` uses a custom, more relaxed nix implementation internally, which it needs to evaluate the hidden flake file that it manages. 
The work  done so far has been to expose to:
1. [Expose this hidden nix binary](https://github.com/cachix/devenv/pull/237/files#diff-59b50cab99afb55f33cc2566a73d3d5d7c74d5f857a64d8257aa5ab224afc9bcR230) (although this will create conflicts with the system one, `devenv which nix` is an alternative implementation)
2. [Add devenv's nix binary to the path](https://github.com/cachix/devenv/pull/237/files#diff-d33e979799a45c7c51752e9c8d96a3e452015d1a40b1e4b6ec6a98e92c4d8430R10-R11)
3. [This way when nix-direnv's `use_flake` runs](https://github.com/cachix/devenv/pull/237/files#diff-d33e979799a45c7c51752e9c8d96a3e452015d1a40b1e4b6ec6a98e92c4d8430R13) when [`nix-direnv` determines which `nix` binary to use](https://github.com/nix-community/nix-direnv/blob/5d735de13814ab9078ebb8323b1b940fd100371e/direnvrc#L12-L13), the correct version is getting picked up
4. Now the part where i'm stuck is how to get [the actual print-dev-env call to consider the devenv managed flake file](https://github.com/nix-community/nix-direnv/blob/5d735de13814ab9078ebb8323b1b940fd100371e/direnvrc#L210-L212), it needs a directory where a normal `flake.nix` file exists, not the dotfile flake file that we is currently used.
   So instead of passing in `.` with `use flake . --impure` we need a different path, an easy way would be to have a `.devenv/flake/flake.nix` symlink file and use `use flake .devent/flake --impure`.
    The last remaining problem with the above is that since that file is actually updated by `devenv`'s `assemble` bash function. We need to call that anytime any of the `nix_direnv_watch`'d files are changed. We would need to extend `nix-direnv` with a `before-print-dev-env` hook, that we could provide.

Any thoughts @domenkozar ?

**Comment by kubukoz** [comment]
0.5 seems to work fine for me.

**Comment by kubukoz** [comment]
(feel free to reopen if needed, I just thought the original issue was solved)
