### ISSUE TITLE
Can't automatically `poetry install --sync` or `poetry install --with dev`

### ISSUE THREAD

**Issue by sersorrel** [cachix/devenv#621]
**Describe the bug**
I use Poetry's dependency groups to separate my project's development dependencies (e.g. mypy, pytest) from runtime dependencies (e.g. flask). To get these installed by Poetry I have to run `poetry install --with dev`, but there's no way to configure devenv to automatically include the `--with dev` when setting `languages.python.poetry.enable = true`, which seriously limits its utility.

Additionally, if I remove a package from my pyproject.toml, it won't be removed from my Poetry-managed virtual environment until I `poetry install --sync` (or in reality, `poetry install --sync --with dev`, else I lose all the dev packages). Again, there's no way to make devenv run this automatically; this results in previously-installed packages hanging around unexpectedly.

**To reproduce**
https://gist.github.com/sersorrel/a5d50dbaed4c0b2566f448ebf15c6d2c

**Version**
devenv: 0.6.2

**Comment by domenkozar** [comment]
@bobvanderlinden do you think it would be possible to support this?

**Comment by mirkolenz** [comment]
I have a similar issue: At the moment, it is not possible to install extras with devenv. Poetry allows one to specify both extras and groups, so it would be great if both are supported 😄

**Comment by bobvanderlinden** [comment]
It is already supported to some extend:

```
languages.python.poetry.install.arguments = [ "--with" "dev" ];
```

I do agree it would be nice to have some convenience options like `languages.python.poetry.install.with = [ "dev" ];` and maybe make that the default.

> Additionally, if I remove a package from my pyproject.toml, it won't be removed from my Poetry-managed virtual environment until I poetry install --sync (or in reality, poetry install --sync --with dev, else I lose all the dev packages).

That's a different problem. I'm guessing you manually remove the package from `pyproject.toml`? The devenv module only looks at the lock file. So, instead of manually editing pyproject.toml, you need to use the command-line commands like:

`poetry add packagename` and `poetry remove packagename`

Otherwise the lock file won't be updated.
If you make changes to `pyproject.toml` manually you'll have to run `poetry lock --no-update` to update the lock file, but not update any packages.

I don't think it's a good idea for devenv to keep track of pyproject.toml. devenv would need to update poetry.lock implicitly, which usually is a git-tracked file. That would be surprising to me.
