### ISSUE TITLE
Support pdm

### ISSUE THREAD

**Issue by domenkozar** [cachix/devenv#703]
For workflows like this: https://gist.github.com/hynek/3f7e759d1fd6e7d94eee456356b1cd72

**Comment by SebastianCallh** [comment]
Hello! I am interested in this landing and just wanted to ask you (since you self-assigned) what the current status is @totoroot ? All the best!

**Comment by totoroot** [comment]
Hi @SebastianCallh :wave:,
Thanks for the reminder!
I've been busy with some other stuff and since we agreed on using poetry at work, I did not have the biggest incentive to work on this.
Seeing that a lot of people voted for it, I'll pick it up again this week in my time off and will try to open a PR soonish :v:

**Comment by totoroot** [comment]
Sorry, I have to admit that I currently neither have resources, nor motivation to work on this, as I'm currently using `poetry` and am exploring `uv` as a faster alternative.
Feel free to pick this issue up if you want to see `pdm` support in devenv.

**Comment by domenkozar** [comment]
In general I think uv is much better, so I'm going to close this. If anyone wants pdm, they can still add it!
