### ISSUE TITLE
dotenv integration captures quotes in value/improperly stores json

### ISSUE THREAD

**Issue by ParetoOptimalDev** [cachix/devenv#772]
**Describe the bug**

When using quoted json in `.env` the resulting environmental variable includes both the quotes and json. If something like "read" in Haskell is called on that environmental variable it will predictably fail.

The reason is because of [this regex in the dotenv integration](https://github.com/theskumar/python-dotenv/issues/35):

```
(.+) *= *(.+)
```

Which results in the single quotes being in the resulting value:

```
nix-repl> builtins.match "(.+) *= *(.+)" "a='{\"a\":\"b\"}'"
builtins.match "(.+) *= *(.+)" "a='{\"a\":\"b\"}'"
[ "a" "'{\"a\":\"b\"}'" ]
```

I can get the expected behavior by optionally matching `'`, but this might not be how you want to write it:

```
nix-repl> builtins.match "(.+) *= *'?(.+)?'" "a='{\"a\":\"b\"}'"
builtins.match "(.+) *= *'?(.+)?'" "a='{\"a\":\"b\"}'"
[ "a" "{\"a\":\"b\"}" ]
```

Some related issues:

https://github.com/theskumar/python-dotenv/issues/35
https://github.com/theskumar/python-dotenv/issues/285
https://github.com/theskumar/python-dotenv/issues/381

**To reproduce**
Please provide an [Short, Self Contained, Correct (Compilable), Example](http://sscce.org) by [creating a gist](https://gist.github.com/) using `devenv.nix`, `devenv.yaml`, and optionally `devenv.lock`.

Given `.env`:

```
data='{"a":"b"}'
```

Running `echo $data` with dotenv integration enabled results in:

```
$ echo $data
'{"a":"b"}'
```

I would expect only the json value and not the surrounding single quotes to be captured.

**Version**
 
Paste the output of `$ devenv version` here.

**Comment by ento** [comment]
https://github.com/cachix/devenv/pull/718 can also fix this issue by offloading the whole parsing logic to the shell. It also means that `config.env` won't hold variables extracted from the .env file, but it's not like `config.env` was guaranteed to hold all the environment variables available in `devenv shell`, since any `enterShell` script can add its own environment variable.

I was looking into tweaking the regex used in `parseLine` to make it ignore comments, but I'm beginning to think #718 may be the smarter approach. (Or at least in that general direction - #718 doesn't handle comments well as-is)

@domenkozar What do you think?

**Comment by RocketPuppy** [comment]
I don't know if this needs a new issue or not, but the regex in question also seems to cause problems with values that have `=` in them. The `"(.+) *= *(.+)"` regex is greedy so everything up to the last `=` is captured as the variable name. For example, a typical database url environment variable such as `DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres?schema=public` seems to be read in with a name of `DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres?schema` instead of the expected name of `DATABASE_URL`.

I will second the ability to have the .env variables accessed in Nix is pretty useful. It lets me easily parameterize parts of an environment variable across environments, such as the port of the database url in the example above.

**Comment by ento** [comment]
Yeah, on second thoughts, I can use direnv to source `.env` if I don't need the env vars to be available in `config.env`.

I have a regex that can handle comments and values with `=` somewhat, but the actual values don't get stripped of comments until after they've been exported as environment variables: https://gist.github.com/ento/765b47da99cc05d4fec508632e8d1f64 (and it doesn't handle quotes at all, as demonstrated by the test cases in that gist)

**Comment by Atry** [comment]
> I will second the ability to have the .env variables accessed in Nix is pretty useful.

I am not sure if it is a good idea to access .env variables in nix expression. For example, if you create a script via `pkgs.writeShellScript` to use `env.DATABASE_URL`, then your pgsql password is leaked to the nix store, which is visible to all unix users. On the other hand, if your shell script reference it via `$DATABASE_URL`, your pgsql password would not be leaked to the nix store.

**Comment by ParetoOptimalDev** [comment]
I just tried this again using `devenv 1.0.8` with a `.env` that looks like:

```
data='{"a":"b"}'
data2="{\"a\":\"b\"}"
data3={"a":"b"}
```

And it looks like `data3` variant works fine, so I also consider this fixed.
