### ISSUE TITLE
language.python.venv.requirements does not support `-r` or `-c` directives

### ISSUE THREAD

**Issue by streadway** [cachix/devenv#889]
**Describe the bug**

language.python.venv.requirements cannot take paths or strings that include `-r` or `-c` directives.

**To reproduce**

1. `echo "requests" > requirements.txt`
2. `echo "-r requirements.txt" > dev.txt`

With this devenv.nix:

```nix
{ pkgs, ... }:
{
  languages.python = {
    enable = true;
    venv = {
      enable = true;
      requirements = ./dev.txt;
    };
  };
}
```
 
```
devenv shell
...
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/nix/store/requirements.txt'
...
```

However when in the shell:

```
> pip install -r dev.txt
Successfully installed certifi-2023.11.17 charset-normalizer-3.3.2 idna-3.6 requests-2.31.0 urllib3-2.1.0
```

**Version**

`devenv: 0.6.3`
 
**Workaround**

We have requirements from multiple locations added a function to interpret the requirements.txt based on the [file format](https://pip.pypa.io/en/stable/reference/requirements-file-format/)

```
{ pkgs, lib, ... }:
let
  # mergeRequirements simulates pip install command "-r"/"-c" parsing
  # requirements.txt paths.
  mergeRequirements = paths:
    with builtins;
    with lib;
    let
      evalLine = dir: line:
        let
          args = strings.splitString " " line;
          command = lists.head args;
          relative = filename: path.append dir filename;
        in
          if command == "-r" || command == "-c"
          then (map evalFile (map relative (lists.tail args)))
          else line;

      evalFile = path: map (evalLine (dirOf path)) (strings.splitString "\n" (readFile path));
      packages = (lists.flatten (map evalFile paths));
    in
      concatStringsSep "\n" packages;
in
{
  languages.python = {
    enable = true;

    venv = {
      enable = true;
      requirements = mergeRequirements [ ./dev.txt ];
    };
  };
}
```

I'm happy to propose a pull request, but would first appreciate advice for an approach.

**Comment by mcdonc** [comment]
For the record, I worked around this using the (somewhat obscure) envvar expansion feature of requirements.txt:

```
-r ${DEVENV_ROOT}/requirements.txt
-e ${DEVENV_ROOT}
```

**Comment by mcdonc** [comment]
> I'm happy to propose a pull request, but would first appreciate advice for an approach.

Hi!

I think this approach will work well.  My Nix isn't as strong as it should be, but I think for this to work right, we actually need to create two derivations (or one derivation with two files in it).. one of the files for requirements (`-r`), and one for constraints (`-c`), because if we put the constraints contents in the requirements, they will be parsed as requirements, not just constraints.

**Comment by mcdonc** [comment]
I worked on this in the context #912, but I couldn't fix it there, so I'll add what I've learned so far about it.

python-rewrite branch only.

Currently, if the devenv venv requirements.txt is a file, and that file has "-r" or "-c" lines, it  won't work at all without something like an envvar e.g. (`-r ${DEVENV_ROOT} requirements2.txt`), because the derivation that is generated for requirements.txt won't have the other files in it.  A pip install will just fail.  I don't think we should rely on envvars at all or recommend other people do either. The environment variable only sorta accidentally works in this case, because it goes behind the back of the requirements derivation when pip install is run on it. 

Here is some Python code that flattens the information from a requirements.txt that references "-c" and "-r" dependencies and generates a flattened requirements.txt and constraints.txt. 

https://gist.github.com/mcdonc/2653bbfbd33032a12464c8f64c183aff

I have not figured out how to create derivation(s) from the output directory of this script, but if we could, it could replace the current requirements derivation.  We could then compare the result of the same script run with the local devenv requirements as input  against the files in the derivation to detect if we need to rerun pip install at `devenv shell` time. 

I was stymied by Nix impurity constraints in all my attempts to do this.

My opinion is that if we don't do this, the "run pip install at `devenv shell` time if there's a requirements file specified and the requirements have changed" feature is kinda useless.

**Comment by streadway** [comment]
Is this a similar problem than the dynamic linker needs to solve - by rewriting imports to their store path?

Instead of collecting/flattening files into requirements.txt and constraints.txt derivations, could an approach be to recursively rewrite the imported -r/-c into store paths from their own derivations?

**Comment by mcdonc** [comment]
> Instead of collecting/flattening files into requirements.txt and constraints.txt derivations, could an approach be to recursively rewrite the imported -r/-c into store paths from their own derivations?

That would be totally reasonable too, except for insane requirements.txt files that name an absolute path as an -r or -c input.  I'm still not sure how to create a derivation from local files of any kind without running into impurity restrictions, though.

**Comment by streadway** [comment]
Rewriting the requirements files when adding them to the store is a bit intrusive. I'm thinking it's better to collect only the sources relevant for pip in the same structure that they're in from the source directory. I'm chipping away on some ideas, currently collecting the dependency tree into a fileset like:

```
  collectRequirements = path:
    let
      lines = lib.splitString "\n" (lib.readFile path);
      collect = acc: line:
        let
          pattern = "[[:space:]]*(-r|-c)[[:space:]]+([^[:space:]]+).*";
          found = builtins.match pattern line;
          required = lib.path.append (dirOf path) (lib.elemAt found 1);
        in
          if found == null then acc
          else lib.fileset.union acc (collectRequirements required);
    in
      lib.foldl collect path lines;
```

**Comment by mcdonc** [comment]
I managed to get this half-working via a Python script in https://github.com/cachix/devenv/pull/964

**Comment by mcdonc** [comment]
https://github.com/cachix/devenv/pull/964 is now fully working.

**Comment by streadway** [comment]
Great! Thanks @mcdonc <3
