### ISSUE TITLE
``devenv info``

### ISSUE THREAD

**Issue by domenkozar** [cachix/devenv#94]
Show environment summary, what scripts/processes/env vars are defined. Proposal:

```shell-session
$ devenv info
# Environment Variables
foo=1
bar=baz

# Scripts
devenv-update-docs
devenv-generate-examples

# Processes
postgres
backend
frontend
```

**Comment by bobvanderlinden** [comment]
Looks good overal. I'm not sure how useful the envvars are if they are part of other options (like Java home, bundler_path or whatever else the modules will set).

The scripts and processes seem to be the parts that users should interact with.

Should users also be informed about the packages (with versions)?

Also, if envs are listed, I was thinking maybe to use titles/names more in line with the options. `env` instead of environment variables. Just a minor thought.

**Comment by rkrzr** [comment]
> Should users also be informed about the packages (with versions)?

I think this would be useful.

Maybe also print which `nix` executable is being used by `devenv` (full path and maybe also version), since setting `languages.nix.enable = true;` can give you a different Nix executable within the devenv, than outside of it.

**Comment by domenkozar** [comment]
Agreed :) What do you think: https://github.com/cachix/devenv/pull/100
